version: '3.1'
services:  
  db:
    # todo: make the image slim using alpine
    build: mysql/
    volumes:
       - ./mysql/mysql_data:/var/lib/mysql # データの永続化
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root #rootパスワードの設定
      - MYSQL_DATABASE=supota
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
  server:
    build: .
    volumes:
      - ./server/:/app/v-doc_server
    ports:
      - "3000:3000"
    links:
      - "db"